/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.bookingDAO;
import DAO.customerDAO;
import DAO.foodDAO;
import Model.DetailFoodOrder;
import Model.FoodOrder;
import Model.customer;
import Model.food;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author T450s
 */
public class foodService extends javax.swing.JFrame {

    /**
     * Creates new form foodService
     */
    public foodService() {
        initComponents();
        jTextField10.setEditable(false);
        jTextField11.setEditable(false);
        jTextField5.setEditable(false);
        jTextField9.setEditable(false);
        autoDate();
        autoTime();
        
        DefaultTableModel mmm = (DefaultTableModel)jTable1.getModel();
        int ind = mmm.getRowCount();
        for(int i = 0; i < ind; i++)
        {
            mmm.setValueAt(0, i, 4);
        }
        
        TableColumn model = jTable1.getColumnModel().getColumn(0);
        JComboBox comboBox = new JComboBox();
        ArrayList<food> listFood = new ArrayList<>();
        foodDAO fd = new foodDAO();
        //foodDAO fdd = new foodDAO();
        //food f = new food();
        listFood = fd.showNotFood();
        for(int i = 0; i < listFood.size(); i++)
        {
            comboBox.addItem(listFood.get(i).getFoodName());
        }
        model.setCellEditor(new DefaultCellEditor(comboBox));
        
        TableColumn model1 = jTable1.getColumnModel().getColumn(3);
        int[] qty = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
        JComboBox comboBox1 = new JComboBox();
        for(int i = 0; i < 10; i++)
        {
            comboBox1.addItem(qty[i]);
        }
        model1.setCellEditor(new DefaultCellEditor(comboBox1));
        
        //String foodName = (String)comboBox.getSelectedItem();
        comboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if(e.getSource() == comboBox)
            {
                String foodName = (String)comboBox.getSelectedItem();
                food f = new food();
                TableModel model1 = jTable1.getModel();
                int index = jTable1.getSelectedRow();
                foodDAO fdd = new foodDAO();
                f.setFoodName(foodName);
                if(fdd.searchFood(f))
                {
                    model1.setValueAt(f.getIdFood(), index, 1);
                    model1.setValueAt(f.getPrice(), index, 2);
                }
                
            }
            }
        });
        
    }
    
    private void autoDate() {
        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jTextField10.setText(s.format(d));
    }

    private void autoTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                java.util.Date d = new java.util.Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                jTextField11.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField10 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Customer Name:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 181, -1, -1));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 178, 202, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Total Price:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 181, -1, -1));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 178, 202, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1226, 23, 36, 36));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Order");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1087, 178, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/foodService.png"))); // NOI18N
        jLabel1.setText("F&B");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Date:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 285, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Food Name", "Food ID", "Price", "Qty", "Amount"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 362, 966, 308));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 282, 202, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Time:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(683, 285, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Room Number:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 83, -1, -1));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 282, 202, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 80, 143, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1087, 282, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG9.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-490, -190, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new foodService().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
            int index = jTable1.getSelectedRow();
            int price = Integer.parseInt(model1.getValueAt(index, 2).toString());
            int qty =  Integer.parseInt(model1.getValueAt(index, 3).toString());
            model1.setValueAt(price * qty, index, 4);
            int index1 = jTable1.getRowCount();
            int sum = 0;
            
            
            for(int i = 0; i < index1; i++)
            {
                sum = sum + Integer.parseInt(model1.getValueAt(i, 4).toString());
            }
            jTextField9.setText(Integer.toString(sum));
            model1.addRow(new Object[]{});
     
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        TableModel model = jTable1.getModel();
        String roomNo = jTextField4.getText();
        String name = jTextField5.getText();
        String orderDate = jTextField10.getText();
        String orderTime = jTextField11.getText();
        String totalPrice = jTextField9.getText();
        customerDAO cd = new customerDAO();
        foodDAO fd = new foodDAO();
        int idCus = cd.searchCustomer(name, roomNo).getIdCus();
        FoodOrder fo = new FoodOrder();
        DetailFoodOrder dfo = new DetailFoodOrder();
        
        
        
        if(name.equals("") || orderDate.equals("")|| orderTime.equals("") || totalPrice.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Every Field is Required");
        }
        else
        {
            fo.setIdCus(idCus);
            fo.setOrderDate(LocalDate.parse(orderDate));
            fo.setOrderTime(orderTime);
            fo.setTotalPrice(Integer.parseInt(totalPrice));
            if(fd.addFoodOrder(fo))
            {
                JOptionPane.showMessageDialog(this, "Add to food order Successfully!");
            }
            
            int idOrder = fd.searchFoodOrder(Date.valueOf(orderDate)).getIdOrder();
            int index = model.getRowCount() - 1;
                    for(int i = 0; i < index; i++)
                    {
                        dfo.setIdOrder(idOrder);
                        dfo.setIdFood(model.getValueAt(i, 1).toString()); 
                        dfo.setQty((Integer)model.getValueAt(i, 3));
                        dfo.setPrice((Integer)model.getValueAt(i, 2));
                        dfo.setAmount((Integer)model.getValueAt(i, 4));
                        if(fd.addDetailFoodOrder(dfo))
                        {
                            //JOptionPane.showMessageDialog(this, "Order Successfully!");
                            if(i == 0)
                            {
                                JOptionPane.showMessageDialog(this, "Order Successfully!");
                            }
                        }
                        if(i == index - 1)
                        {
                            setVisible(false);
                            new foodService().setVisible(true);
                        }
                    }
            
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String roomNo = jTextField4.getText();
        if(roomNo.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Room Number Field Is Required!");
        }
        else
        {
            customer cus = new customer();
            bookingDAO bd = new bookingDAO();            
            cus = bd.searchCheckinRoom(roomNo);
            jTextField5.setText(cus.getName());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(foodService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new foodService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
